Register.destroy_all
Register.create(name: 'Apprentice assessment organisation', phase: 'Backlog', authority: 'Department for Education')
Register.create(name: 'Authorised Individual Savings Account manager', phase:'Backlog', authority: 'HM Revenue & Customs')
Register.create(name: 'Charity', phase:'Backlog', authority: 'Charity Commission')
Register.create(name: 'Civil marriage and civil partnership venue', phase:'Backlog', authority: 'Home Office')
Register.create(name: 'Clinical commissioning group', phase: 'Discovery', authority: 'NHS Business Services Authority')
Register.create(name: 'Company', phase:'Backlog', authority: 'Companies House')
Register.create(name: 'Counting rules for reported crimes', phase:'Backlog', authority: 'Home Office')
Register.create(name: 'Country', phase: 'Beta', authority: 'Foreign & Commonwealth Office')
Register.create(name: 'Court and tribunal', phase:'Backlog', authority: 'Ministry of Justice')
Register.create(name: 'Datatype', phase: 'Beta', authority: 'Cabinet Office')
Register.create(name: 'Dental practice', phase:'Backlog', authority: 'NHS Business Services Authority')
Register.create(name: 'Family mediator', phase:'Backlog', authority: 'Ministry of Justice')
Register.create(name: 'Field', phase: 'Beta', authority: 'Cabinet Office')
Register.create(name: 'Fire authority', phase:'Backlog', authority: 'Home Office')
Register.create(name: 'Fire station', phase:'Backlog', authority: 'Home Office')
Register.create(name: 'Food authority', phase:'Backlog', authority: 'Food Standards Agency')
Register.create(name: 'Foreign Office posts', phase:'Backlog', authority: 'Foreign & Commonwealth Office')
Register.create(name: 'Further education establishment', phase:'Backlog', authority: 'Department for Education')
Register.create(name: 'Government domain', phase: 'Discovery', authority: 'Cabinet Office')
Register.create(name: 'Government organisation', phase: 'Beta', authority: 'Cabinet Office')
Register.create(name: 'Government service', phase: 'Beta', authority: 'Cabinet Office')
Register.create(name: 'Government website', phase:'Backlog', authority: 'Cabinet Office')
Register.create(name: 'GP practice', phase:'Backlog', authority: 'NHS')
Register.create(name: 'Green deal certification body', phase: 'Discovery', authority: 'Department for Business, Energy & Industrial Strategy')
Register.create(name: 'Higher education establishment', phase:'Backlog', authority: 'Department for Education')
Register.create(name: 'Industrial classification', phase: 'Alpha', authority: 'Government Statistical Service')
Register.create(name: 'Internal drainage board', phase: 'Beta', authority: 'Department for Environment, Food & Rural Affairs')
Register.create(name: 'Jobcentre', phase: 'Discovery', authority: 'Department for Work and Pensions')
Register.create(name: 'Local authority eng', phase: 'Beta', authority: 'Department for Communities and Local Government')
Register.create(name: 'Local authority nir', phase: 'Discovery', authority: 'Government Digital Service')
Register.create(name: 'Local authority sct', phase: 'Beta', authority: 'Scottish Government')
Register.create(name: 'Local authority type', phase: 'Beta', authority: 'Department for Communities and Local Government')
Register.create(name: 'Notifiable animal disease', phase: 'Alpha', authority: 'Department for Environment, Food & Rural Affairs')
Register.create(name: 'Notifiable animal disease confirmation category', phase: 'Alpha', authority: 'Department for Environment, Food & Rural Affairs')
Register.create(name: 'Notifiable animal disease investigation category', phase: 'Alpha', authority: 'Department for Environment, Food & Rural Affairs')
Register.create(name: 'Occupation', phase: 'Alpha', authority: 'Government Statistical Service')
Register.create(name: 'Police force', phase:'Backlog', authority: 'Home Office')
Register.create(name: 'Police station', phase:'Backlog', authority: 'Home Office')
Register.create(name: 'Principal local authority', phase: 'Beta', authority: 'Welsh Government')
Register.create(name: 'Prison estate', phase: 'Beta', authority: 'Ministry of Justice')
Register.create(name: 'Qualification', phase:'Backlog', authority: 'Department for Education')
Register.create(name: 'Register', phase: 'Beta', authority: 'Cabinet Office')
Register.create(name: 'Register office', phase:'Backlog', authority: 'HM Passport Office')
Register.create(name: 'Registration district', phase: 'Beta', authority: 'HM Passport Office')
Register.create(name: 'School Eng', phase: 'Alpha', authority: 'Department for Education')
Register.create(name: 'School Wales', phase:'Backlog', authority: 'Welsh government')
Register.create(name: 'Social housing provider', phase: 'Alpha', authority: 'Homes and Communities Agency')
Register.create(name: 'Statistical Geography', phase: 'Discovery', authority: 'Office for National Statistics')
Register.create(name: 'Territory', phase: 'Beta', authority: 'Foreign & Commonwealth Office')
Register.create(name: 'UK', phase:'Backlog', authority: 'Foreign & Commonwealth Office')
Register.create(name: 'Vehicle category', phase:'Backlog', authority: 'Department for Transport')
Register.create(name: 'Vehicle colour', phase: 'Discovery', authority: 'Driver and Vehicle Licensing Agency')
Register.create(name: 'Vehicle fuel type', phase:'Backlog', authority: 'Department for Transport')
Register.create(name: 'Vehicle make', phase:'Backlog', authority: 'Department for Transport')
